apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.app.frontend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.frontend.service.port }}
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.app.backend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.backend.service.port }}
      targetPort: 8888
  selector:
    app: {{ .Release.Name }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: {{ .Values.app.db.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.db.service.port }}
      targetPort: 27017
  selector:
    app: {{ .Release.Name }}-db

